#!/bin/bash
# OpenFlaw Generator Helper
# Usage: ./generate-openflaw.sh <person|software|org> <name> [depth]

TYPE="$1"
NAME="$2"
DEPTH="${3:-brief}"

if [ -z "$TYPE" ] || [ -z "$NAME" ]; then
    echo "Usage: ./generate-openflaw.sh <person|software|org> <name> [depth]"
    echo "  depth: brief (default) or deep"
    exit 1
fi

OUTPUT_FILE="OpenFlaw-$(echo "$NAME" | tr ' ' '-' | tr '[:upper:]' '[:lower:]').md"

echo "# OpenFlaw: $NAME

*Generated by OpenClaw using #OpenFlaw principles*

---

## Subject: $NAME
**Type:** $TYPE
**Research Depth:** $DEPTH
**Generated:** $(date '+%Y-%m-%d')

---

## Summary

[To be filled after research]

## Known Flaws / Transparency Record

### Flaw 1: [Name]

- **The Flaw:** [Description]
- **The Feature:** [How it's useful]
- **Evidence:** [Links, quotes]
- **Mitigation:** [What they do about it]

---

## Verdict

[Does this subject embody #OpenFlaw principles?]

---

*Generated using the OpenFlaw methodology. Claims should be verified.*
" > "$OUTPUT_FILE"

echo "Created: $OUTPUT_FILE"
echo "Edit it with research findings, then run: cat $OUTPUT_FILE"
